version: '3.8'

services:
  web:
    build:
      dockerfile: ${DOCKERFILE:-Dockerfile}
    ports:
      - "8000:8000"
      - "5678:5678"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql+asyncpg://${DATABASE_USER}:${DATABASE_PASSWORD}@db:5432/${DATABASE_NAME}
      - DEBUG=true
    command: ["sh", "-c", "poetry run alembic upgrade head && poetry run python -m debugpy --wait-for-client --listen 0.0.0.0:5678 -m uvicorn seazone.main:app --host 0.0.0.0 --port 8000"]


  db:
    image: postgres:14
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
volumes:
  postgres_data:
