"""change created_at fiel default value

Revision ID: d200e0c9ec19
Revises: 810a3c9c2e44
Create Date: 2025-03-10 22:16:34.938356

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd200e0c9ec19'
down_revision: Union[str, None] = '810a3c9c2e44'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
