"""add total_price field

Revision ID: d836ddb915ca
Revises: 113c7bb9c6b0
Create Date: 2024-10-20 23:35:20.444297

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd836ddb915ca'
down_revision: Union[str, None] = '113c7bb9c6b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reservation', sa.Column('total_price', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reservation', 'total_price')
    # ### end Alembic commands ###
